name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # runs daily at 3 AM UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          destination-folder: .
